### ISSUE TITLE
Server: საჭიროა შეიქმნას Table (PeaceOfArt)

### ISSUE THREAD

**Issue by lashatsatsashvili** [lashatsatsashvili/Graphite-Server#3]
საჭიროა შეიქმნას ციხრილი ნამუშევრებისთვის ველებით:
1)id
2)user_id
3)pic_name
4)title
5)description
6) longitude
7) latitude
8)category_id
9)create_date

**Comment by oalkhanishvili** [comment]
6) longitude
7) latitude

შეცდომაა double არ ამახსოვრებს კოორდინატებს ბოლომდე. ამრგვალებს ჯობია var_char ჩაწერო

**Comment by lashatsatsashvili** [comment]
ok var charad gadavaketeb

**Comment by oalkhanishvili** [comment]
da kide longiture da lalitude adgilebi sheicvale jer latitudaa mere longi
